//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buffet.DAO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADON
    {
        public int MaChiTietHoaDon { get; set; }
        public Nullable<int> SoLuongLay { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public Nullable<int> MaDoUong { get; set; }
        public Nullable<int> MaHoaDon { get; set; }
    
        public virtual DOUONG DOUONG { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
