//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buffet.DAO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOANHTHU
    {
        public int MaDoanhThu { get; set; }
        public string TenDoanhThu { get; set; }
        public System.DateTime NgayDoanhThu { get; set; }
        public string NhanVienDoanhThu { get; set; }
        public decimal TongDoanhThu { get; set; }
        public Nullable<int> MaHoaDon { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
