//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buffet.DAO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
            this.DOANHTHUs = new HashSet<DOANHTHU>();
        }
    
        public int MaHoaDon { get; set; }
        public string TenKhachHang { get; set; }
        public int SoLuongKhach { get; set; }
        public string BanKhachHang { get; set; }
        public Nullable<System.DateTime> ThoiGianKhachVao { get; set; }
        public Nullable<decimal> GiaSetBuffet { get; set; }
        public Nullable<decimal> TongPhiDoUong { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<int> Thue { get; set; }
        public Nullable<int> GiamGia { get; set; }
        public Nullable<decimal> TienThanhToan { get; set; }
        public Nullable<decimal> SoTienNhan { get; set; }
        public Nullable<decimal> SoTienTraKhach { get; set; }
        public Nullable<System.DateTime> ThoiGianHoaDon { get; set; }
        public Nullable<bool> TinhTrangHoaDon { get; set; }
        public Nullable<int> MaBanAn { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
    
        public virtual BANAN BANAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOANHTHU> DOANHTHUs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
