//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buffet.DAO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CuaHangBuffetEntities : DbContext
    {
        public CuaHangBuffetEntities()
            : base("name=CuaHangBuffetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        internal BANAN Find(int maBanAn)
        {
            throw new NotImplementedException();
        }

        public virtual DbSet<BANAN> BANAN { get; set; }
        public virtual DbSet<DANHMUCDOUONG> DANHMUCDOUONG { get; set; }
        public virtual DbSet<DANHMUCMONAN> DANHMUCMONAN { get; set; }
        public virtual DbSet<DOANHTHU> DOANHTHU { get; set; }
        public virtual DbSet<DOUONG> DOUONG { get; set; }
        public virtual DbSet<HOADON> HOADON { get; set; }
        public virtual DbSet<KHO> KHO { get; set; }
        public virtual DbSet<LOAISANPHAMKHO> LOAISANPHAMKHO { get; set; }
        public virtual DbSet<MONAN> MONAN { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIEN { get; set; }
        public virtual DbSet<PHANQUYEN> PHANQUYEN { get; set; }
        public virtual DbSet<QUANTRIVIEN> QUANTRIVIEN { get; set; }
        public virtual DbSet<SANPHAMKHO> SANPHAMKHO { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOAN { get; set; }
    }
}
