//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buffet.DAO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAMKHO
    {
        public int MaSanPhamKho { get; set; }
        public string TenSanPhamKho { get; set; }
        public string LoaiSanPhamKho { get; set; }
        public string DonViTinh { get; set; }
        public int SoLuong { get; set; }
        public string NguoiNhapKho { get; set; }
        public string NguoiCapNhat { get; set; }
        public bool TinhTrangSpKho { get; set; }
        public Nullable<int> MaLoaiSanPhamKho { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
    
        public virtual LOAISANPHAMKHO LOAISANPHAMKHO1 { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
